site_name: COMP423 Course Notes
theme:
  name: material
  features:
    - content.code.copy
  palette:
    primary: teal
    accent: cyan
    theme: default
  icon:
    admonition:
      note: octicons/tag-16
      info: octicons/info-16


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences